security:
    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:

        ROLE_STUDENT: [ROLE_USER, ROLE_STUDENT]
        ROLE_SUPER_STUDENT: [ROLE_RELATION, ROLE_STUDENT, ROLE_SUPER_STUDENT]
        ROLE_STUDENT_HIRED: [ROLE_RECRUIT, ROLE_STUDENT, ROLE_SUPER_STUDENT, ROLE_STUDENT_HIRED]
        
        ROLE_COMPANY: [ROLE_USER, ROLE_COMPANY]
        ROLE_SUPER_COMPANY: [ROLE_RELATION, ROLE_COMPANY, ROLE_SUPER_COMPANY]

        ROLE_SCHOOL: [ROLE_USER, ROLE_SCHOOL]
        ROLE_SUPER_SCHOOL: [ROLE_SCHOOL, ROLE_SUPER_SCHOOL]

        ROLE_ADMIN: [ROLE_USER, ROLE_SUPER_STUDENT, ROLE_STUDENT_HIRED, ROLE_SUPER_COMPANY, ROLE_SUPER_SCHOOL, ROLE_ADMIN]

        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SUPER_STUDENT, ROLE_STUDENT_HIRED, ROLE_SUPER_COMPANY, ROLE_SUPER_SCHOOL, ROLE_ADMIN]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\UserControllerAuthenticator

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                    
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/student, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        # - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # catch all other URLs
        - { path: '^/', requires_channel: https }
